autyzm-pg/friendly-plans

- docs/dev/android Studio Instrukcja.md
Propozycja instrukcji importowania projektu do Android Studio. Dla mnie zadziałało.
> Dodaję propozycję instrukcji importowania projektu

- src/PlanManager/build.gradle
- src/app2/src/main/java/com/przyjaznyplan/repositories/DatabaseUtils.java
- src/app2/src/main/java/com/przyjaznyplan/repositories/UserRepository.java
- src/appManager/build.gradle
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/TestUtils.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Users/UserListViewTest.java
- src/appManager/src/main/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Users/UserListView.java
- src/appManager/src/main/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Utils/UserAdapter.java
- src/appManager/src/main/res/layout/users_list_view.xml
- src/build.gradle
- src/gradle/wrapper/gradle-wrapper.properties
- Add test for displaying users
- Fix filtering users ( I couldn't write working fine test, Sorry)
- Some gradle imports has been changed ( because  of tests ), please check if it is working for you
- Should I add gradle-wrapper to gitignore? we have this on repo, but Android studio has changed it for me.
> Fix filter in users list, add test

- src/app2/src/main/java/com/przyjaznyplan/repositories/UserRepository.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/TestUtils.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Users/EditUserViewTest.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Users/UserListViewTest.java
- Delete method from user repository
- Change testUtil to create user object and then insert it to db by repository
- Add closing keyboard for test to run on other tablets, which show keyboard as full screen
- Add cleaning after test
- Rename filter test
#33
> User repository refactor - issue 33

- src/app2/src/main/java/com/przyjaznyplan/repositories/ActivityRepository.java
- src/app2/src/main/java/com/przyjaznyplan/repositories/UserRepository.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/PlanActions/ActionsListViewTest.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/TestUtils.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Users/EditUserViewTest.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Users/UserListViewTest.java
- src/appManager/src/main/AndroidManifest.xml
- src/appManager/src/main/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Aktywnosci/ActivityEditView.java
- src/appManager/src/main/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Czynnosci/ActionListView.java
- src/appManager/src/main/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Utils/SlidesAdapter.java
- src/appManager/src/main/res/layout/action_list.xml
- src/appManager/src/main/res/layout/row_list_layout.xml
- Add edit action button to adapter
- Add test for calling edit
#28
> Fix edit action bug

- src/app2/src/main/java/com/przyjaznyplan/dao/ActivityDao.java
- src/app2/src/main/java/com/przyjaznyplan/repositories/ActivityRepository.java
- src/app2/src/main/java/com/przyjaznyplan/repositories/UserRepository.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/PlanActions/ActionsListViewTest.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/PlanActions/EditActionTest.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/PlanActivities/ActivityEditViewTest.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/TestUtils.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Users/EditUserViewTest.java
- src/appManager/src/androidTest/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Users/UserListViewTest.java
- src/appManager/src/main/AndroidManifest.xml
- src/appManager/src/main/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Aktywnosci/ActivityEditView.java
- src/appManager/src/main/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Czynnosci/ActionAddEditView.java
- src/appManager/src/main/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Czynnosci/ActionListView.java
- src/appManager/src/main/java/com/przyjaznyplanDisplayer/mymodule/appmanager/Utils/SlidesAdapter.java
- src/appManager/src/main/res/layout/action_edit_view.xml
- src/appManager/src/main/res/layout/action_list.xml
- src/appManager/src/main/res/layout/activity_edit_view.xml
- src/appManager/src/main/res/layout/row_list_layout.xml
- src/appManager/src/main/res/values/strings.xml
Add test for Activity edit view.
> Tests for activity edit view

- README.md
Add whitespace between hashtag and header text
> #113: Fix readme headers

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/AssetTestRule.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/TaskCreateActivityTest.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/matchers/ErrorTextMatcher.java
- Friendly-plans/app/src/main/java/database/repository/TaskTemplateRepository.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/TaskContainerFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/asset/AssetType.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/file_picker/FilePickerProxy.java
- Friendly-plans/app/src/main/res/layout/fragment_task_container.xml
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/activity/TaskCreateActivityTest.java
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/asset/AssetTypeTest.java
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/database/TaskTemplateRepositoryTest.java
resolved: #73
- Add choosing sound in task create activity
- Save sound id to db
> 73 add sound to task

- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/asset/AssetType.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/file_picker/FilePickerProxy.java
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/file_picker/FilePickerProxyTest.java
> #153: Fix choosing file in file picker, change regex, add tests

- .travis.yml
- Friendly-plans/app/build.gradle
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/ImagePreviewDialog.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/TaskContainerFragment.java
- Friendly-plans/app/src/main/res/layout/fragment_task_container.xml
- Friendly-plans/app/src/main/res/layout/picture_full_size_preview_dialog.xml
Please review the code and let discuss following things:
0. Grid layout is stretched
2. click out of border on preview window happens nothing
3. left\right empty space on preview dialog
1. problem with Espresso tests:  assetTestRule.setTestPicture(); - picture is set in different way then user does.
> #134 The icon of selected picture and its preview (on click) is added.

- Friendly-plans/app/build.gradle
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/MainActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/MainActivityEvents.java
- Friendly-plans/app/src/main/res/layout/activity_main.xml
1) Add data binding library.
2) Convert the first screen to fully use data binding, aka moved all of the click methods to it's own interface which the activity implements, so we don't give the XML full access to modify the `activity`.
Ref: https://github.com/autyzm-pg/friendly-plans/issues/146
> [DataBinding] Add dependency and also make the main screen fully use it

- doc/ui-model.md
Old link was invalid, mockup version has changed and project needed to be migrated. 
resolves #163
> 163: Update link in ui model readme

- Friendly-plans/app/src/main/java/database/repository/StepTemplateRepository.java
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/database/StepTemplateRepositoryTest.java
> 129: Add create and get all steps method in StepTemplateRepository

- Friendly-plans/app/src/main/res/layout/fragment_step_list.xml
- Friendly-plans/app/src/main/res/layout/item_step.xml
List for steps mocks were added. Ref: #126
> 126: create xml mock for steps list

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/TaskCreateActivityTest.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/TaskCreateActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/TaskCreateFragment.java
- Friendly-plans/app/src/main/res/layout/fragment_task_menu.xml
- Move toast displaying action into 'Next' button on click handler
- Add checking is toast displayed to adding task test
- Unify handling of toast in TaskCreateFragment
resolves #74
> #74 Fix notification about saving task

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/StepListFragmentTest.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/TaskTemplateRule.java
- Friendly-plans/app/src/main/java/database/repository/RepositoryModule.java
- Friendly-plans/app/src/main/java/database/repository/StepTemplateRepository.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/AppComponent.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/StepListFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/StepListRecyclerViewAdapter.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/TaskCreateFragment.java
- Friendly-plans/app/src/main/res/layout/fragment_step_list.xml
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/database/StepTemplateRepositoryTest.java
> 125 create steps list java fragment

- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/TaskRecyclerViewAdapter.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/asset/AssetsHelper.java
Please test on real device. Images are taken from storage and displayed at the recycleView task list. 
I decided to leave the placeholder image in case if it was not selected.  
Resolves: #137
> #137 Images are displayed in task list.

- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/StepCreateFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/StepListFragment.java
- Friendly-plans/app/src/main/res/layout/fragment_step_create.xml
- Friendly-plans/app/src/main/res/values/strings.xml
> #124: Create connection from step list to create new step.

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/StepCreateFragmentTest.java
- Friendly-plans/app/src/main/res/layout/fragment_step_create.xml
- Friendly-plans/app/src/main/res/values/strings.xml
> #124 Add xml mock for StepCreateFragment

- README.md
Fixed some small english syntax and semantics in the README to improve the overall quality of the text.
> Improve readme file.

- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/asset/AssetType.java
Title says all.
Also changed the constant naming a bit so it makes more sense now. Hope that's fine.
> Good practice - compile constant regex patterns once.

- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_create/TaskCreateFragment.java
- Friendly-plans/app/src/main/res/layout/activity_main.xml
- Friendly-plans/app/src/main/res/layout/fragment_step_list.xml
- Friendly-plans/app/src/main/res/values/strings.xml
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/activity/TaskCreateActivityTest.java
> #117: Implements handling exceptions when inserting task

- README.md
Fixed broken link to PCDI videos page.
> #194: Fix broken link

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/TaskCreateActivityEditModeTest.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_create/TaskCreateActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_create/TaskCreateFragment.java
- Pass bundle as args to fragment
- Get task id from bundle
- Update form if necessary
- Test
Resolves #177
> #177: Display task information in form when task's id passed to the fragment

- Friendly-plans/app/build.gradle
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/AppComponent.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/step_create/StepCreateEvents.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/step_create/StepCreateFragment.java
- Friendly-plans/app/src/main/res/layout/fragment_step_create.xml
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/activity/StepCreateFragmentTest.java
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/activity/TaskCreateActivityTest.java
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/asset/AssetsHelperTest.java
- Bind onClick event with handler
- Add playing/stopping sound logic to fragment
- Update Robolectric version to handle Android Binding
- Test
No test for checking is sound played properly because of I still didn't figure out how test sound with Espresso/Robolectric...
Resolves #140
> #140: Play sound assigned to step on button click

- README.md
Add badge to slack and update like to slack invitation app.
> #83 add slackin link

- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_create/TaskCreateActivityEvents.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_create/TaskCreateFragment.java
- Friendly-plans/app/src/main/res/layout/fragment_task_create.xml
Modified TaskCreateActivity to use data binding (more info in issue #146)
> 175: Changed TaskCreateActivity to use DataBinding

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/TaskCreateActivityTest.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/validation/TaskValidation.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/validation/Validation.java
1. Moved _TaskTemplateRepository_ object to _TaskValidation_ class
2. Modified _Validation_ class to abstract
3. Moved name validation to _Validation_ class
> 231: modified Validation class to be activity independent

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/StepCreateFragmentTest.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/TaskCreateActivityTest.java
- Friendly-plans/app/src/main/java/database/repository/StepTemplateRepository.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/step_create/StepCreateData.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/step_create/StepCreateEvents.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/step_create/StepCreateFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/step_list/StepListFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_create/TaskCreateFragment.java
- Friendly-plans/app/src/main/res/layout/fragment_step_create.xml
- Friendly-plans/app/src/main/res/values/strings.xml
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/activity/StepCreateFragmentTest.java
- README.md
Another attempt to pull commits prepared by @paulamoller:
- Fixed conflicts
- Save step name to db
- Add perform this action to button save
- Tests
> 131: Storing a new Step into db

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/StepListFragmentTest.java
- Friendly-plans/app/src/main/java/database/repository/StepTemplateRepository.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/item_touch_helper/ItemTouchHelperAdapter.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/item_touch_helper/ItemTouchHelperViewHolder.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/item_touch_helper/SimpleItemTouchHelperCallback.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/step_list/StepListFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/step_list/StepListRecyclerViewAdapter.java
- Friendly-plans/app/src/main/res/drawable/ic_reorder_black_24dp.xml
- Friendly-plans/app/src/main/res/layout/item_step.xml
- Friendly-plans/app/src/main/res/values/strings.xml
- README.md
- Changing order of steps assign to the task using drag and drop
- Removing step using swipe
Code uses ItemTouchHelper, and is based on example provided by Paul Burke (Apache Licence 2.0)
> #240: Changing order of steps assign to the task

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/StepCreateFragmentTest.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/components/SoundComponent.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/step_create/StepCreateFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_create/TaskCreateFragment.java
- Friendly-plans/app/src/main/res/layout/fragment_step_create.xml
- Friendly-plans/app/src/main/res/layout/fragment_task_create.xml
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/activity/StepCreateFragmentTest.java
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/view/components/SoundComponentTest.java
- README.md
1. Update SoundComponent with soundId, after selecting sound file in StepCreateFragment and TaskCreateFragment.
2. Replaced ImageView and Button pair with ImageButton for playing sound in StepCreateFragment and TaskCreateFragment.
> 247: Fixing sound component to play sound

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/PlanCreateActivityTest.java
- Friendly-plans/app/src/main/java/database/repository/PlanTemplateRepository.java
- Friendly-plans/app/src/main/java/database/repository/RepositoryModule.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/AppComponent.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create/PlanCreateActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create/PlanCreateActivityEvents.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create/PlanCreateData.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create/PlanCreateFragment.java
- Friendly-plans/app/src/main/res/layout/fragment_plan_create.xml
- Friendly-plans/app/src/main/res/values/strings.xml
- added data binding to plan's name field
- added planTemplateRepository
- added save plan name to db action after clicking next button 
- added test
> 238 create plan add name to db

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/PlanListActivityTest.java
- Friendly-plans/app/src/main/AndroidManifest.xml
- Friendly-plans/app/src/main/java/database/repository/PlanTemplateRepository.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/AppComponent.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/main_screen/MainActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/main_screen/MainActivityEvents.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_list/PlanListActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_list/PlanRecyclerViewAdapter.java
- Friendly-plans/app/src/main/res/layout/activity_main.xml
- Friendly-plans/app/src/main/res/layout/activity_plan_list.xml
- Friendly-plans/app/src/main/res/layout/item_plan.xml
- createing xml mock and empty fragment
- displaying all plan templates from db 
- adding test
resolves: #257 and #258
> #257: List of plans - create xml mock and display all plan templates

- .travis.yml
- Friendly-plans/app/build.gradle
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/StepCreateFragmentTest.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/TaskCreateActivityTest.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/annotations/IgnoreForTravis.java
> 251 add ignore for travis annotation

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/StepCreateFragmentTest.java
- Friendly-plans/app/src/main/java/database/repository/StepTemplateRepository.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/App.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/validation/StepValidation.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/validation/ValidationModule.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/step_create/StepCreateFragment.java
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/activity/StepCreateFragmentTest.java
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/test_helpers/AppComponentBuilder.java
- StepValidation class is added
- Validation of the step name added to StepCreate activity
- New tests in StepCreateFragmentTest (Espresso)
- AppComponentBuilder extended to work with new StepValidation (Mockito)
- StepCreateFragmentTest tests based on TaskCreateFragmentTest (Mockito)
Resolves #252
> #252: Validation for step create

- Friendly-plans/app/src/main/AndroidManifest.xml
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/AppComponent.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/file_picker/FilePickerProxy.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_create/TaskCreateActivity.java
- Friendly-plans/app/src/main/res/values/strings.xml
Checks external storage permission, if not granted, asks user to allow access. 
Resolves #246
> #246: manage permission for external storage access

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/AddTasksToPlanFragmentTest.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/AppComponent.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create_add_tasks/AddTasksToPlanFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create_task_list/PlanTaskListEvents.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create_task_list/PlanTaskListFragment.java
- Friendly-plans/app/src/main/res/layout/fragment_add_tasks_to_plan.xml
- Friendly-plans/app/src/main/res/values/strings.xml
> #242: Create plan, select tasks - create xml mock and empty fragment 

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/PlanCreateActivityTest.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/validation/PlanValidation.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/validation/ValidationModule.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create/PlanCreateData.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create/PlanCreateFragment.java
- Friendly-plans/app/src/test/java/pg/autyzm/friendly_plans/validation/PlanValidationTest.java
- Implement PlanValidation based on TaskValidation
- Check is name valid during Plan creation, display simple toast message
Simple toast for now cause I had a problem with binding the error message...
> #267: Plan name validation

- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create/PlanCreateFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/step_create/StepCreateFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/task_create/TaskCreateFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/view_fragment/CreateFragment.java
Class CreateFregment includes several methods and fields extracted from TaskCreateFregment and StepCreateFregment.
>  #205: Extracted common methods and fields from *CreateFragments

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/PlanListActivityTest.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/TaskListActivityTest.java
- Friendly-plans/app/src/main/java/database/repository/PlanTemplateRepository.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/ActivityProperties.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create/PlanCreateActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_create/PlanCreateFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_list/PlanListActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/view/plan_list/PlanRecyclerViewAdapter.java
1. Clicking a plan in the plan list opens CreatePlanFragment with values from database.
2. Clicking the Next button saves modifications to the database.
Resolves #259
> #259: Allows modification of an already-created plan.

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/manager_app/PlanListActivityTest.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/manager_app/TaskListActivityTest.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/resource/ChildViewClicker.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/view_actions/ViewClicker.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/plan_create_add_tasks/AddTasksToPlanFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/plan_create_task_list/PlanTaskListFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/task_list/TaskListActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/task_list/TaskRecyclerViewAdapter.java
- Friendly-plans/app/src/main/res/layout/item_task.xml
- Friendly-plans/app/src/main/res/values/strings.xml
Added an option to delete a Task from the Task List in a similar way to how it is done with Plans. (#319)
Added a test to check if Task is indeed being deleted, and took some code from _PlanListActivityTest_ to a newly created class _ChildViewClicker_, since it is now needed in _TaskListActivityTest_ as well.
A screenshot of the Task List after changes:
> 319 task deleting

- Friendly-plans/app/src/main/res/layout/fragment_step_create.xml
- Friendly-plans/app/src/main/res/values/strings.xml
> #332: Remove cancel button

- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/plan_list/PlanListActivity.java
> #343: a fix for multiple plans removal list refreshing

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/manager_app/ActivatePlanActivityTest.java
- Friendly-plans/app/src/main/AndroidManifest.xml
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/AppComponent.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/activate_plan/ActivatePlanActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/activate_plan/ActivatePlanRecyclerViewAdapter.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/main_screen/MainActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/main_screen/MainActivityEvents.java
- Friendly-plans/app/src/main/res/layout/activate_plan.xml
- Friendly-plans/app/src/main/res/layout/activity_main.xml
- Friendly-plans/app/src/main/res/values/strings.xml
Added the "activate plan" menu item and activity XML.
Created a simple test class for the new activity for later use, featuring, as for now, the description and button visibility check and plan items displaying check.
Resolves #350
> 350 active plan view creation

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/manager_app/ChildListActivityTest.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/child_list/ChildListActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/child_list/ChildRecyclerViewAdapter.java
- Friendly-plans/app/src/main/res/values/strings.xml
> #295: Remove child profile

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/manager_app/AddTasksToPlanFragmentTest.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/manager_app/PlanCreateActivityTest.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/manager_app/PlanListActivityTest.java
- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/manager_app/PlanTaskListFragmentTest.java
- Friendly-plans/app/src/main/java/database/repository/PlanTemplateRepository.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/ActivityProperties.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/plan_create/PlanCreateActivityEvents.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/plan_create/PlanCreateFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/plan_create_add_tasks/AddTasksToPlanFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/plan_create_task_list/PlanTaskListFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/task_create/TaskCreateFragment.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/task_type_enum/TaskType.java
- Friendly-plans/app/src/main/res/layout/fragment_add_tasks_to_plan.xml
- Friendly-plans/app/src/main/res/layout/fragment_plan_create.xml
- Friendly-plans/app/src/main/res/layout/fragment_plan_menu.xml
- Friendly-plans/app/src/main/res/layout/fragment_plan_task_list.xml
- Friendly-plans/app/src/main/res/values/strings.xml
Resolves: #345, #346, #347, #348, #349
> 345 create plan display list of tasks

- Friendly-plans/app/src/androidTest/java/pg/autyzm/friendly_plans/manager_app/ChildListActivityTest.java
- Friendly-plans/app/src/main/java/database/entities/Child.java
- Friendly-plans/app/src/main/java/database/repository/ChildRepository.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/child_list/ChildListActivity.java
- Friendly-plans/app/src/main/java/pg/autyzm/friendly_plans/manager_app/view/child_list/ChildRecyclerViewAdapter.java
- Friendly-plans/app/src/main/res/layout/activity_child_list.xml
- Friendly-plans/app/src/main/res/values/strings.xml
> #298: Select active child
